### PR TITLE
Handle Assert.Count for missing elements correctly. Fixes #110

### LINKED ISSUE #110: I.Assert.Count() not working when no item
`I.Assert.Count` passes when the selector return nothing, even if you're expecting an item.

So `I.Assert.Count(1).Of("#dummy")` passes even if no element with an id of dummy is present in the page.

I suspect the try/catch in the Count method to be responsible for eating the exception, but I haven't had time to test my theory yet.

### PR DESCRIPTION
**Pull request by pauljz**

### CODE REVIEW

**Comment by jbblanchet** [comment]
That was quick! Just wanted to know if there would be a release soon for this fix since it's kind of major, or should I build it on my end?

**Comment by stirno** [comment]
I'll merge the PR and it'll hit nuget with the official v3.0 release tonight or tomorrow.

**Comment by jbblanchet** [comment]
Did I just get a scoop about the release date for 3.0? ;)

Nice, I'll plan a few hours tomorrow in case there's any breaking changes.

Thanks for the good work.

**Comment by stirno** [comment]
Fixing a slightly different way that cleans up some cruft from v2 at the same time.

**Pull request closed without merging**
