### PR TITLE
Fix for #132 that @predeekc suggested

### PR DESCRIPTION
**Pull request by scmccart**
Hey, this is the fix for #132 that @predeekc suggested, it fixed some issues we were seeing caused by jQuery being overwritten.

### CODE REVIEW

**Comment by stirno** [comment]
Going to pull together a few more fixes and push a new version to nuget this weekend. Thanks for the PR @scmccart and @predeekc

**Comment by olidyu** [comment]
@scmccart , The change @predeekc suggested actually is not the idea fix.

The original code was calling the "jQuery.noConflict()" at the end of the injected code, trying to prevent the window.$ and window.jQuery pollute. However, it is missing a param specification.
If we look at the code of the method:

```
noConflict: function( deep ) {
    if ( window.$ === jQuery ) {
        window.$ = _$;
    }
    if ( deep && window.jQuery === jQuery ) {
        window.jQuery = _jQuery;
    }

    return jQuery;
}
```

It is not handling the window.jQuery when the param "deep" is not specified.
So the only change needed, is to change the 

```
window.fluentjQuery = jQuery.noConflict();
```

into:

```
window.fluentjQuery = jQuery.noConflict(true);
```

This way is more complete fix for this issue. In case the window.jQuery is a variable that is not actually jQuery.

**Comment by scmccart** [comment]
@olidyu Can do, how about the typeof checks? should they be using jQuery instead of window.jQuery?

**Comment by olidyu** [comment]
@scmccart I'm not getting ur question here. If we change the "jQuery.noConflict(true);", we would not need the typeof check anymore.
What I was suggesting is to utilize the jQuery lib way to avoid pollute, instead of checking them in the c# code.
Sorry for the late response. I don't visit here very often.

**Comment by Smoothjadesa** [comment]
The fix for #132  is not working for us. We keep getting jquery 1.7.2 on window.jQuery. We've tried "jQuery.noConflict(true);" but it didn't work either. Only thing that worked was to replace the compiledSizzleSource with jQuery 1.12.4 - the version used on our project.

**Pull request merged**
