### PR TITLE
Updated the chromedriver binary to 2.25

### PR DESCRIPTION
**Pull request by pdesjardins90**
"chromedriver.exe has stopped working" when running fluent tests since the last chrome update. 
=> After investigation, an updated chromedriver binary should fix this issue.

### CODE REVIEW

**Comment by pdesjardins90** [comment]
@stirno Are you still accepting PRs or this repo is dead?

**Comment by ffMathy** [comment]
I think he killed it off.

**Comment by csharpforevermore** [comment]
That's such a shame! What do you recommend in its place?

**Comment by pdesjardins90** [comment]
We completely changed stack since I closed this issue, so we haven't looked in a c# alternative

**Pull request closed without merging**
